apiVersion: v1
kind: Service
metadata:
  name: book-search
spec:
  type: NodePort
  selector:
  # select the pods with labels.name : book-search-app 
  # (book-search.yaml :: metadata.labels.name: book-search-app)
    name: book-search-app
  ports:
  - name: svc-port-frontend
    port: 5000
    # book-search.yml::frontend's containerPort:5000 -name: frontend-port
    targetPort: frontend-port
    # 30000(nodePort) -> 5000 (port) -> 5000 (targetPort)
    nodePort: 30000
  - name: svc-port-backend
    port: 3000
    # book-search::backend's containerPort: 3000 -name: backend-port
    targetPort: backend-port
    # 30300 -> 3000 -> 3000
    nodePort: 30300
    
